### ISSUE TITLE
初学者问题

### ISSUE THREAD

**Issue by callmelex** [NanGC/CNN#1]
打扰了
请问为什么文件夹用"CK-_part"，而不是"CK+_part"
能不能给一个测试的代码，测试一张指定的图片什么的，多谢了

**Comment by callmelex** [comment]
我在网上找了测试代码，好像是你的
    logit = inference(test_batch, BATCH_SIZE, N_CLASSES)
但这里好像有问题

**Comment by callmelex** [comment]
加了from Model import inference，还是有问题
真是步履艰难啊。。。

**Comment by callmelex** [comment]
ValueError: could not convert string to float: '********/CK+_part/surprised/83.jpg'
实在不懂问题在哪

**Comment by 1denglei** [comment]
> ValueError: could not convert string to float: '********/CK+_part/surprised/83.jpg'
> 实在不懂问题在哪

我也是这个问题，不知道老哥你解决了没？

**Comment by NanGC** [comment]
名称这个没有关系的，只要代码里里面保持一致就好了。代码问题，后来陆续做了更新，可参看。抱歉才回复。
